x-common: &common
  build:
    args:
      - NODE_VER=22.11.0
    context: .
    dockerfile: Dockerfile
  tty: true
  volumes:
    - .:/home/node/app
    - ./node_modules:/home/node/app_node_modules
  environment:
    - CHOKIDAR_USEPOLLING

services:
  web:
    <<: *common
    ports:
      - 3000:3000
    command: npm run dev

volumes:
  node_modules:
